# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: E2E CI/CD Checks

on:
  pull_request:
    branches: [ "main" ]
    types: [ assigned, opened, edited, reopened, synchronize ]

permissions:
  contents: read

jobs:
  test-remote-runnable:
    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ClearML
        run: |
          python -m pip install --upgrade pip clearml
          sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Start the task
        id: launch_task
        run: |
          echo "TASK_ID=$(
            clearml-task --project 'Loan Approval V6' --name cicd_test --branch ${{ github.head_ref }} --script ci_cd_check_task.py --requirements requirements.txt --skip-task-init --queue cicd_queue | rg -o 'Task id=(.*) sent' -r '$1'
          )" >> $GITHUB_OUTPUT
      - name: Poll for task progress
        run: python runnable_cicd.py "${{ steps.launch_task.outputs.TASK_ID }}"